### ISSUE TITLE
Markdown parsing fails on Kotlin/JS

### ISSUE THREAD

**Issue by sureshg** [JetBrains/markdown#78]
The basic example given in the project page is fails to run on Kotlin/JS application with `Invalid regular expression` error.

```kotlin
val src = "Some *markdown*"
val flavour = GFMFlavourDescriptor()
val parsedTree = MarkdownParser(flavour).buildMarkdownTreeFromString(src)
val html = HtmlGenerator(src, parsedTree, flavour).generateHtml()
log("Markdown : $html")
```

Version Used:
```kotlin
 kotlin("js") version "1.5.0-RC"
 implementation("org.jetbrains:markdown:0.2.2")
```

```kotlin
kotlin_kotlin.js?215f:19299 SyntaxError: Invalid regular expression: /^ {0,3}(\-+|=+) *$/: Invalid escape
    at new RegExp (<anonymous>)
    at Regex (webpack-internal:///./kotlin/kotlin_kotlin.js:18373:26)
    at Regex_init_$Init$_0 (webpack-internal:///./kotlin/kotlin_kotlin.js:18294:11)
    at Regex_init_$Create$_0 (webpack-internal:///./kotlin/kotlin_kotlin.js:18298:12)
    at new Companion_126 (webpack-internal:///./kotlin/kotlin_org_jetbrains_markdown.js:9168:21)
    at Companion_getInstance_125 (webpack-internal:///./kotlin/kotlin_org_jetbrains_markdown.js:9181:7)
    at new SetextHeaderProvider (webpack-internal:///./kotlin/kotlin_org_jetbrains_markdown.js:9185:5)
    at GFMMarkerProcessor.CommonMarkMarkerProcessor [as constructor] (webpack-internal:///./kotlin/kotlin_org_jetbrains_markdown.js:1234:122)
    at new GFMMarkerProcessor (webpack-internal:///./kotlin/kotlin_org_jetbrains_markdown.js:1875:31)
    at Factory_1.createMarkerProcessor_1 (webpack-internal:///./kotlin/kotlin_org_jetbrains_markdown.js:1861:12)
 ```

**Comment by ajalt** [comment]
I reported this as [KT-46694](https://youtrack.jetbrains.com/issue/KT-46694), although it should be possible to workaround this issue in the meantime.

**Comment by NebuPookins** [comment]
What's the workaround? To just downgrade to 1.4?

**Comment by ajalt** [comment]
The workaround from this library would be to adjust the regex to avoid the bug. For users of this library right now, I think you're correct that the only solution is to downgrade to Kotlin 1.4.
